[package]

name = "glutin"
version = "0.0.1"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]

[dependencies.compile_msg]
git = "https://github.com/huonw/compile_msg"

[dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"

[dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

[dependencies.cocoa]
git = "https://github.com/servo/rust-cocoa"
